export const TYPES = {
  // ── Services (capa data) ──
  AuthService: Symbol.for('AuthService'),
  MotorcycleService: Symbol.for('MotorcycleService'),
  MotoStatsService: Symbol.for('MotoStatsService'),
  RouteService: Symbol.for('RouteService'),
  DirectionsService: Symbol.for('DirectionsService'),
  FuelStationService: Symbol.for('FuelStationService'),
  LocationService: Symbol.for('LocationService'),
  PlaceSearchService: Symbol.for('PlaceSearchService'),
  PlaceCategorySearchService: Symbol.for('PlaceCategorySearchService'),
  PlaceSummaryService: Symbol.for('PlaceSummaryService'),
  ElevationService: Symbol.for('ElevationService'),
  RouteShareService: Symbol.for('RouteShareService'),
  ShareCodeGeneratorService: Symbol.for('ShareCodeGeneratorService'),
  TripPartyService: Symbol.for('TripPartyService'),

  // ── Repositories (contrato en domain, impl en data) ──
  AuthRepository: Symbol.for('AuthRepository'),
  MotorcycleRepository: Symbol.for('MotorcycleRepository'),
  MotoStatsRepository: Symbol.for('MotoStatsRepository'),
  RouteRepository: Symbol.for('RouteRepository'),
  DirectionsRepository: Symbol.for('DirectionsRepository'),
  FuelStationRepository: Symbol.for('FuelStationRepository'),
  LocationRepository: Symbol.for('LocationRepository'),
  PlaceSearchRepository: Symbol.for('PlaceSearchRepository'),
  PlaceCategorySearchRepository: Symbol.for('PlaceCategorySearchRepository'),
  PlaceSummaryRepository: Symbol.for('PlaceSummaryRepository'),
  RecentDestinationRepository: Symbol.for('RecentDestinationRepository'),
  ElevationRepository: Symbol.for('ElevationRepository'),
  RouteShareRepository: Symbol.for('RouteShareRepository'),
  TripPartyRepository: Symbol.for('TripPartyRepository'),

  // ── UseCases (capa domain) ──
  SignUpUseCase: Symbol.for('SignUpUseCase'),
  SignInUseCase: Symbol.for('SignInUseCase'),
  SignOutUseCase: Symbol.for('SignOutUseCase'),
  GetCurrentRiderUseCase: Symbol.for('GetCurrentRiderUseCase'),
  ObserveAuthStateUseCase: Symbol.for('ObserveAuthStateUseCase'),
  GetAllMotorcyclesUseCase: Symbol.for('GetAllMotorcyclesUseCase'),
  GetMotorcycleUseCase: Symbol.for('GetMotorcycleUseCase'),
  CreateMotorcycleUseCase: Symbol.for('CreateMotorcycleUseCase'),
  UpdateMotorcycleUseCase: Symbol.for('UpdateMotorcycleUseCase'),
  DeleteMotorcycleUseCase: Symbol.for('DeleteMotorcycleUseCase'),
  FetchMotorcycleSpecsUseCase: Symbol.for('FetchMotorcycleSpecsUseCase'),
  GetAllRoutesUseCase: Symbol.for('GetAllRoutesUseCase'),
  GetRouteUseCase: Symbol.for('GetRouteUseCase'),
  CreateRouteUseCase: Symbol.for('CreateRouteUseCase'),
  UpdateRouteUseCase: Symbol.for('UpdateRouteUseCase'),
  DeleteRouteUseCase: Symbol.for('DeleteRouteUseCase'),
  CalculateDirectionsUseCase: Symbol.for('CalculateDirectionsUseCase'),
  EstimateAutonomyUseCase: Symbol.for('EstimateAutonomyUseCase'),
  FindFuelStationsUseCase: Symbol.for('FindFuelStationsUseCase'),
  RequestLocationPermissionUseCase: Symbol.for(
    'RequestLocationPermissionUseCase',
  ),
  GetCurrentLocationUseCase: Symbol.for('GetCurrentLocationUseCase'),
  WatchLocationUseCase: Symbol.for('WatchLocationUseCase'),
  WatchHeadingUseCase: Symbol.for('WatchHeadingUseCase'),
  SearchPlacesUseCase: Symbol.for('SearchPlacesUseCase'),
  SearchPlacesByCategoryUseCase: Symbol.for('SearchPlacesByCategoryUseCase'),
  GetPlaceSummaryUseCase: Symbol.for('GetPlaceSummaryUseCase'),
  GetRecentDestinationsUseCase: Symbol.for('GetRecentDestinationsUseCase'),
  AddRecentDestinationUseCase: Symbol.for('AddRecentDestinationUseCase'),
  ClearRecentDestinationsUseCase: Symbol.for('ClearRecentDestinationsUseCase'),
  GetRouteElevationUseCase: Symbol.for('GetRouteElevationUseCase'),
  EstimateRouteFuelUseCase: Symbol.for('EstimateRouteFuelUseCase'),
  InferStopKindUseCase: Symbol.for('InferStopKindUseCase'),
  GenerateRouteShareCodeUseCase: Symbol.for('GenerateRouteShareCodeUseCase'),
  ResolveRouteShareCodeUseCase: Symbol.for('ResolveRouteShareCodeUseCase'),
  RevokeRouteShareCodeUseCase: Symbol.for('RevokeRouteShareCodeUseCase'),
  CreateTripPartyUseCase: Symbol.for('CreateTripPartyUseCase'),
  JoinTripPartyUseCase: Symbol.for('JoinTripPartyUseCase'),
  LeaveTripPartyUseCase: Symbol.for('LeaveTripPartyUseCase'),
  ObserveTripPartyUseCase: Symbol.for('ObserveTripPartyUseCase'),

  // ── ViewModels (capa ui) ──
  SessionViewModel: Symbol.for('SessionViewModel'),
  AuthViewModel: Symbol.for('AuthViewModel'),
  GarageViewModel: Symbol.for('GarageViewModel'),
  MotorcycleFormViewModel: Symbol.for('MotorcycleFormViewModel'),
  RoutesViewModel: Symbol.for('RoutesViewModel'),
  RoutePlannerViewModel: Symbol.for('RoutePlannerViewModel'),
  RouteDetailViewModel: Symbol.for('RouteDetailViewModel'),
  HomeViewModel: Symbol.for('HomeViewModel'),
  DestinationPreviewViewModel: Symbol.for('DestinationPreviewViewModel'),
  JoinRouteViewModel: Symbol.for('JoinRouteViewModel'),
  PartyMembersViewModel: Symbol.for('PartyMembersViewModel'),
  LocationStore: Symbol.for('LocationStore'),
  TripPartyStore: Symbol.for('TripPartyStore'),
} as const;
